### ISSUE TITLE
ModuleNotFoundError: No module named 'edsnlp.matchers.phrase' once edsnlp is installed using pip in conda environment

### ISSUE THREAD

**Issue by gozat** [aphp/edsnlp#61]
## Description

Can not load spacy model once edsnlp is installed in my virtual environment created using (mini)conda. Installation of spacy via mamba

## How to reproduce the bug

```python
import spacy

nlp = spacy.blank("fr")

# ...
```
Note no edsnlp-module is called

Returns 
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda3/envs/spacy/lib/python3.9/site-packages/spacy/__init__.py", line 74, in blank
    return LangClass.from_config(config, vocab=vocab, meta=meta)
  File "~/miniconda3/envs/spacy/lib/python3.9/site-packages/spacy/language.py", line 1749, in from_config
    nlp = lang_cls(vocab=vocab, create_tokenizer=create_tokenizer, meta=meta)
  File "~/miniconda3/envs/spacy/lib/python3.9/site-packages/spacy/language.py", line 162, in __init__
    util.registry._entry_point_factories.get_all()
  File "~/miniconda3/envs/spacy/lib/python3.9/site-packages/catalogue/__init__.py", line 109, in get_all
    result.update(self.get_entry_points())
  File "~/miniconda3/envs/spacy/lib/python3.9/site-packages/catalogue/__init__.py", line 124, in get_entry_points
    result[entry_point.name] = entry_point.load()
  File "~/miniconda3/envs/spacy/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "~/miniconda3/envs/spacy/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "~/Documents/edsnlp/edsnlp/components.py", line 1, in <module>
    from edsnlp.pipelines.factories import *  # noqa : used to import pipelines
  File "~/Documents/edsnlp/edsnlp/pipelines/factories.py", line 2, in <module>
    from .core.advanced.factory import create_component as advanced
  File "~/Documents/edsnlp/edsnlp/pipelines/core/advanced/__init__.py", line 1, in <module>
    from .advanced import AdvancedRegex
  File "~/Documents/edsnlp/edsnlp/pipelines/core/advanced/advanced.py", line 9, in <module>
    from edsnlp.pipelines.core.matcher import GenericMatcher
  File "~/Documents/edsnlp/edsnlp/pipelines/core/matcher/__init__.py", line 1, in <module>
    from .matcher import GenericMatcher
  File "~/Documents/edsnlp/edsnlp/pipelines/core/matcher/matcher.py", line 6, in <module>
    from edsnlp.matchers.phrase import EDSPhraseMatcher
ModuleNotFoundError: No module named 'edsnlp.matchers.phrase'

```

## Your Environment

- Operating System: Linux Ubuntu 
- Python Version Used: 3.9.1
- spaCy Version Used: 3.2.1
- EDS-NLP Version Used: 0.5.1
- Environment Information: conda environment, using mamba to install spacy and spyder, then using pip to install edsnlp

**Comment by gozat** [comment]
Using conda/mamba, I got no trouble using

```bash
mamba create --name spacy python==3.9
sudo -H ~/miniconda3/envs/spacy/bin/pip install --upgrade pip
sudo -H ~/miniconda3/envs/spacy/bin/pip install -r requirements.txt
sudo -H ~/miniconda3/envs/spacy/bin/pip install -r requirements-setup.txt
```
